---
  
  name: build & deploy
  
  on:
    # Déclenchement de l'action lors d'un push sur la branche main ou par déclenchement manuel
    workflow_dispatch:
    push:
      branches:
        - main
  
  jobs:
    # Compilation du projet
    build:
      runs-on: ubuntu-latest
      steps:
        # Récupération des fichiers
        - name: Checkout repository
          uses: actions/checkout@v4
  
        # Chargement de l'image Go
        - name: Setup Go
          uses: actions/setup-go@v5
          with:
            go-version: '1.23.x'
  
        # Installation des dépendances
        - name: Install dependencies
          run: |
            [ -f go.mod ] || go mod init cowsay
            go mod tidy
  
        # Compilation et nommage du fichier binaire
        - name: Build
          run: go build -o file-bin ./
  
        # Téléchargement du fichier binaire en tant qu'artifact
        - name: Upload compiled binary
          uses: actions/upload-artifact@v4
          with:
            name: compiled-binary
            # recuperation du fichier binaire
            path: ./deploy/file-bin
  
        # Verifier la presence du fichier
        - name: Verify upload artifact
          run: |
            ls -l ./

    # Déploiement du projet
    deploy:
      runs-on: go marti
      needs: build
      steps:
        # Télécharge l'artefact et le place dans le répertoire courant
        - name: Download artifact 
          uses: actions/download-artifact@v4
          with:
            # 'path' définit où le fichier artefact sera téléchargé sur la machine où l'action s'exécute.
            # Ici, on le télécharge dans le répertoire courant du job, soit './'.
            path: ./
            name: compiled-binary

        # Verifier la presence du fichier
        - name: Verify download artifact
          run: |
            ls -l ./

        # Déplacer l'artefact téléchargé à la racine du dossier utilisateur
        - name: Deploy to target directory
          run: |
            mv ./compiled-binary /home/student/
            chmod +x /home/student/compiled-binary
        
        # Verifier la presence du fichier
        - name: Verify deployment
          run: |
            ls -l /home/student