name: build & deploy

on:
  # Déclenchement de l'action lors d'un push sur la branche main ou par déclenchement manuel
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  # Compilation du projet
  build:
    runs-on: ubuntu-latest
    steps:
      # Récupération des fichiers
      - name: Checkout repository
        uses: actions/checkout@v4

      # Chargement de l'image Go
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.x'

      # Installation des dépendances
      - name: Install dependencies
        run: |
          [ -f go.mod ] || go mod init cowsay
          go mod tidy

      # Compilation et nommage du fichier binaire
      - name: Build
        run: go build -o file-bin ./  

      # Téléchargement du fichier binaire en tant qu'artifact
      - name: Upload compiled binary
        uses: actions/upload-artifact@v3
        with:
          name: compiled-binary
          path: ./file-bin


# Déploiement du projet
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Téléchargement de l'artifact (fichier binaire compilé)
      - name: Download compiled binary
        uses: actions/download-artifact@v3
        with:
          name: compiled-binary  # Correspond au nom de l'artifact téléchargé
          path: ./  # Téléchargement dans le répertoire courant

      # Test de connexion SSH avec appleboy/ssh-action
      - name: Test SSH connection using appleboy/ssh-action
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: itdeveloppement-server.eddi.cloud
          username: student
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Test de la connexion SSH au serveur"
            echo "Connexion réussie à $(hostname)"

  # # Déploiement du projet
  # deploy:
  #    runs-on: ubuntu-latest
  #    needs: build
  #    steps:

  #      # Configuration de la clé SSH pour le déploiement
  #      - name: SSH key
  #        uses: webfactory/ssh-agent@v0.5.3
  #        with:
  #          ssh-private-key: xxxxx

  #      # Téléchargement de l'artifact (fichier binaire compilé)
  #      - name: Download compiled binary
  #        uses: actions/download-artifact@v3
  #        with:
  #         name: compiled-binary  # Correspond au nom de l'artifact téléchargé
  #         path: ./  # Téléchargement dans le répertoire courant

  #      # Copie du fichier binaire vers le serveur distant
  #      - name: Copy binary to server
  #        run: |
  #          scp ./file-bin student@itdeveloppement-server.eddi.cloud:~/deploy/

  #      # Exécution du fichier binaire sur le serveur
  #      - name: Execute the compiled binary on server
  #        run: |
  #         ssh student@itdeveloppement-server.eddi.cloud "sudo chmod +x ~/deploy/file-bin && ~/deploy/file-bin"
