---
  
  name: build & deploy
  
  on:
    # Déclenchement de l'action lors d'un push sur la branche main ou par déclenchement manuel
    workflow_dispatch:
    push:
      branches:
        - main
  
  jobs:
    # Compilation du projet
    build:
      runs-on: ubuntu-latest
      steps:
        # Récupération des fichiers
        - name: Checkout repository
          uses: actions/checkout@v4
  
        # Chargement de l'image Go
        - name: Setup Go
          uses: actions/setup-go@v5
          with:
            go-version: '1.23.x'
  
        # Installation des dépendances
        - name: Install dependencies
          run: |
            [ -f go.mod ] || go mod init cowsay
            go mod tidy
  
        # Compilation et nommage du fichier binaire
        - name: Build
          run: go build -o file-bin ./
  
        # Téléchargement du fichier binaire en tant qu'artifact
        - name: Upload compiled binary
          uses: actions/upload-artifact@v4
          with:
            name: compiled-binary
            path: ./
  
    # Déploiement du projet
    deploy:
      runs-on: go marti
      needs: build
      steps:
        - name: Download artifact 
          uses: actions/download-artifact@v4
          with:
            path: ./
            name: compiled-binary

        - name: Deploy to target directory
        # Déplacer l'artefact téléchargé à la racine du dossier utilisateur
          run: |
           mv ./app /home/student/
           chmod +x /home/student/app
              
        - name: Verify deployment
          run: |
            ls -l /home/sutdent